### ISSUE TITLE
Doesn't look good on side drawer

### ISSUE THREAD

**Issue by odeialba** [santoshndev/moodle-block_site_stats#1]
If I add the block in the side drawer of the dashboard, it does not look good:
<img width="347" alt="Captura de pantalla 2024-05-08 a las 13 45 22" src="https://github.com/santoshndev/moodle-block_site_stats/assets/8805948/092f5a98-a200-4aef-8019-ab9d72c22a1a">

**Comment by santoshndev** [comment]
Hi @odeialba 
The issue has been fixed.. Please review the same.
