### ISSUE TITLE
Remove strings from the code

### ISSUE THREAD

**Issue by odeialba** [santoshndev/moodle-block_site_stats#3]
There shouldn't be any string at all in the code. You can use translation strings instead ('sizemb' and 'sizegb').

https://github.com/santoshndev/moodle-block_site_stats/blob/803624aabd2fdc64597e89e9783d953b11a0b64e/classes/output/main.php#L97

**Comment by santoshndev** [comment]
Hi @odeialba 
Thanks for the review.. I have fixed the issues.. Please review the same.
