### ISSUE TITLE
Fix coding style

### ISSUE THREAD

**Issue by odeialba** [santoshndev/moodle-block_site_stats#4]
The moodle plugin style checker has some style errors that should be fixed. https://moodle.org/plugins/block_site_stats/2024050400/31959?smurf=html

You can check the coding style here https://moodledev.io/general/development/policies/codingstyle

**Comment by santoshndev** [comment]
Hi @odeialba 
Thanks for the review.. I have already fixed these issues in the updated version. Please find the code prechecks here: https://moodle.org/plugins/block_site_stats/1.0.1/32025?smurf=html
